<a href="https://colab.research.google.com/github/ngohuy1811/AIO-Module-4/blob/main/Linear_%26_non_linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#1b
#2b
#3d
#4b
def r2score ( y_pred , y ):
    rss = np . sum (( y_pred - y ) ** 2)
    tss = np . sum (( y - y . mean () ) ** 2)
    r2 = 1 - ( rss / tss )
    return r2

In [3]:
y_pred = np.array([1,2,3,4,5])
y = np.array([1,2,3,4,5])
print(r2score (y_pred,y))

y_pred2 = np.array([1,2,3,4,5])
y2 = np.array([3,5,5,2,4])
print(r2score (y_pred2,y2))

1.0
-2.235294117647059


In [ ]:
#5b
#6b


In [4]:
import numpy as np
#7a
def create_polynomial_features(X , degree =2):
    X_new = X
    for d in range(2, degree+1):
        X_new = np.c_[ X_new, np.power(X, d) ]
    return X_new

X = np.array ([[1],[2],[3]])
print(create_polynomial_features (X, degree =2))


[[1 1]
 [2 4]
 [3 9]]


In [5]:
#8a
def create_polynomial_features2(X, degree=2):
    X_mem = []
    for X_sub in X.T:
        X_new = X_sub
        for d in range(2, degree+1):
            X_new = np.c_[X_new, np.power(X_sub, d)]
        X_mem.extend(X_new.T)
    return np.c_[X_mem].T



In [6]:
X = np.array([[1 , 2] , [2 , 3] , [3 , 4]])
print(create_polynomial_features2(X, degree=2))


[[ 1  1  2  4]
 [ 2  4  3  9]
 [ 3  9  4 16]]


In [21]:
!gdown 1A8kK0IEsT3w8htzU18ihFr5UV-euhquC

Downloading...
From: https://drive.google.com/uc?id=1A8kK0IEsT3w8htzU18ihFr5UV-euhquC
To: /content/SalesPrediction.csv
100% 206k/206k [00:00<00:00, 62.9MB/s]


In [22]:
import pandas as pd
import numpy as np


df = pd.read_csv('/content/SalesPrediction.csv')
df = pd.get_dummies(df)

In [23]:
# Handle Null values
df = df.fillna(df.mean())

In [24]:
# Get features
X = df[['TV','Radio','Social Media','Influencer_Macro','Influencer_Mega','Influencer_Micro','Influencer_Nano']]
y = df['Sales']

In [25]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

In [26]:
#10a
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_processed = scaler.fit_transform(X_train)
X_test_processed = scaler.transform(X_test)
scaler.mean_ [0]

54.173577723283785

In [27]:
from sklearn.preprocessing import PolynomialFeatures

poly_features = PolynomialFeatures(degree=2)

X_train_poly = poly_features.fit_transform(X_train_processed)
X_test_poly = poly_features.transform(X_test_processed)

In [28]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

poly_model = LinearRegression()
poly_model.fit(X_train_poly , y_train)

preds = poly_model.predict(X_test_poly)
r2_score (y_test,preds)

0.9951796158547627